export const Joblist = [
  {
      id: "3e7c3f6d-bdf9-45df-9c1a-58bde12f5d2c",
      job_title: "Nhân Viên Nghiên Cứu Và Phát Triển (R&D Dược Phẩm)",
      job_link: "https://example.com/jobs/rd-duoc-pham",
      salary: "Thỏa thuận theo năng lực và kinh nghiệm",
      region: "Hà Nội",
      job_company: "Công ty TNHH Novopharm",
      experience: "Không yêu cầu kinh nghiệm, sẽ được đào tạo bài bản",
      job_level: "Nhân viên",
      education_level: "Đại học Dược Hà Nội - chuyên ngành CÔNG NGHIỆP DƯỢC",
      related_job: "Dược phẩm/Công nghệ sinh học, R&D y dược, Kiểm nghiệm dược phẩm, Bào chế",
      required_skills: "Bào chế dược phẩm, Kiểm nghiệm, Nghiên cứu phát triển công thức, Theo dõi độ ổn định, Xây dựng tiêu chuẩn chất lượng",
      job_description: "Xây dựng đề xuất công thức, pha thử, theo dõi độ ổn định, xây dựng tiêu chuẩn kiểm nghiệm kiểm soát chất lượng sản phẩm, cải tiến công thức.\n\nPhối hợp với trưởng bộ phận và các phòng ban liên quan (training, marketing) để nghiên cứu, xây dựng bào chế sản phẩm mới như thuốc, mỹ phẩm, thực phẩm bảo vệ sức khỏe.\n\nTriển khai sản xuất, tham gia chuyển giao và theo dõi quá trình sản xuất tại nhà máy GMP Dược phẩm tại Hà Nam (khi có lịch sản xuất, có xe đưa đón).\n\nNghiên cứu đề xuất các máy móc liên quan đến nghiên cứu, sản xuất sản phẩm liên quan.\n\nTham gia một phần vào công việc chuẩn bị hồ sơ đăng ký của các sản phẩm nghiên cứu.",
      job_requirement: "Tốt nghiệp Đại học Dược Hà Nội - chuyên ngành Công Nghiệp Dược.\n\nLàm luận văn tốt nghiệp liên quan đến bào chế hoặc kiểm nghiệm là một lợi thế.\n\nKhông yêu cầu kinh nghiệm, sẽ được đào tạo bài bản.\n\nCó khả năng làm việc độc lập và làm việc nhóm tốt.\n\nCẩn thận, tỉ mỉ, có tinh thần trách nhiệm cao trong công việc.\n\nCó khả năng nghiên cứu, tìm hiểu và áp dụng các kiến thức chuyên môn vào thực tiễn.",
      job_benefit: "Cơ hội trải nghiệm toàn diện công việc R&D dược phẩm từ A-Z.\n\nĐào tạo bài bản, phát triển bản thân và phát huy tối đa sở trường.\n\nMôi trường làm việc thân thiện, chuyên nghiệp, năng động, khuyến khích sáng tạo.\n\nĐầy đủ BHXH, BHYT, BHTN theo quy định ngay khi ký hợp đồng.\n\nNhân viên làm việc đủ thâm niên được mua thêm bảo hiểm y tế tự nguyện cho mình và người thân.\n\nThu nhập cạnh tranh, ổn định (với các bạn đã có kinh nghiệm trên 1 năm).\n\nThưởng KPIs và thưởng theo sản lượng khi sản phẩm đi vào sản xuất.\n\nThưởng các dịp lễ, Tết, sinh nhật, hiếu, hỷ, ốm đau.\n\nDu lịch hàng năm cùng công ty, tham gia các chương trình team building hàng quý.\n\nHỗ trợ ăn trưa, gửi xe, trang thiết bị làm việc 100%.\n\nPhụ cấp điện thoại và được cấp máy tính làm việc.",
      work_location: "47BT2 Nguyễn Duy Trinh, Hoàng Mai, Hà Nội (Văn phòng chính)\nNhà máy GMP Dược phẩm tại Hà Nam (khi có lịch sản xuất, có xe đưa đón)"
  },
  {
    id: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
    job_title: "Lập Trình Viên Frontend",
    job_link: "https://example.com/jobs/frontend-dev",
    salary: "80.000.000 - 110.000.000 VNĐ",
    region: "Thành phố Hồ Chí Minh",
    job_company: "Công ty Cổ phần TechVision",
    experience: "2-4 năm",
    job_level: "Chuyên viên",
    education_level: "Cử nhân Công nghệ thông tin hoặc tương đương",
    related_job: "Lập trình web, Phát triển giao diện người dùng",
    required_skills: "JavaScript, TypeScript, React, CSS, HTML",
    job_description: "Chúng tôi đang tìm kiếm một Lập trình viên Frontend tài năng để tham gia vào đội ngũ năng động của công ty. Bạn sẽ chịu trách nhiệm xây dựng các thành phần giao diện và tương tác với người dùng.\n\nTham gia vào quá trình thiết kế, phát triển và tối ưu hóa các ứng dụng web đáp ứng.\n\nPhối hợp chặt chẽ với các nhà thiết kế và nhóm phát triển backend để đảm bảo tính nhất quán của giao diện.\n\nThực hiện kiểm thử và đảm bảo chất lượng code, khắc phục lỗi và cải thiện hiệu suất ứng dụng.\n\nCập nhật và áp dụng các công nghệ mới, xu hướng phát triển frontend hiện đại vào dự án.",
    job_requirement: "Thành thạo HTML, CSS, JavaScript và các framework hiện đại.\n\nKinh nghiệm làm việc với thiết kế responsive và tương thích đa trình duyệt.\n\nHiểu biết sâu về React và TypeScript, cùng các thư viện liên quan.\n\nKỹ năng tối ưu hóa hiệu suất trang web, SEO cơ bản.\n\nKinh nghiệm làm việc với REST API và GraphQL.\n\nCó khả năng giao tiếp tốt, làm việc nhóm hiệu quả và giải quyết vấn đề độc lập.",
    job_benefit: "Thời gian làm việc linh hoạt, chế độ chăm sóc sức khỏe toàn diện.\n\nThưởng thành tích cuối năm hấp dẫn.\n\nCơ hội phát triển chuyên môn và tham gia các khóa học nâng cao kỹ năng.\n\nMôi trường làm việc trẻ trung, năng động và sáng tạo.\n\nCơ hội tham gia các dự án quốc tế với công nghệ tiên tiến.\n\nChế độ nghỉ phép linh hoạt, hoạt động team building thường xuyên.",
    work_location: "Quận 1, Thành phố Hồ Chí Minh"
  },
  {
    id: "3e7c3f6d-bdf9-45df-9c1a-58bde12f5d2c",
    job_title: "Kỹ Sư Phát Triển Backend",
    job_link: "https://example.com/jobs/backend-engineer",
    salary: "90.000.000 - 130.000.000 VNĐ",
    region: "Hà Nội",
    job_company: "Công ty TNHH Hệ Thống DataFlow",
    experience: "3-5 năm",
    job_level: "Chuyên viên cao cấp",
    education_level: "Cử nhân hoặc Thạc sĩ Khoa học máy tính",
    related_job: "Kỹ sư phần mềm, Phát triển API",
    required_skills: "Python, Django, PostgreSQL, Redis, Docker",
    job_description: "Chúng tôi đang tìm kiếm một Kỹ sư Backend có kinh nghiệm để phát triển và duy trì các hệ thống cốt lõi. Bạn sẽ tham gia thiết kế API, xây dựng cấu trúc cơ sở dữ liệu và đảm bảo hiệu suất cao của hệ thống.\n\nXây dựng và duy trì các dịch vụ backend, API và microservices.\n\nThiết kế và tối ưu hóa cơ sở dữ liệu, đảm bảo khả năng mở rộng và hiệu suất.\n\nPhối hợp với đội ngũ frontend để tích hợp các tính năng mới.\n\nXây dựng quy trình CI/CD, đảm bảo chất lượng code và hạ tầng.",
    job_requirement: "Chuyên môn cao về Python và ít nhất một framework Python.\n\nHiểu biết vững chắc về cơ sở dữ liệu, cơ chế caching và kiến trúc máy chủ.\n\nKinh nghiệm với các công cụ container hóa như Docker và Kubernetes.\n\nKỹ năng tối ưu hóa hiệu suất và khả năng mở rộng của ứng dụng.\n\nKinh nghiệm làm việc trong môi trường Agile/Scrum.\n\nKhả năng giải quyết vấn đề phức tạp và tư duy hệ thống tốt.",
    job_benefit: "Mức lương cạnh tranh, cơ hội nhận cổ phần công ty.\n\nCơ hội làm việc từ xa linh hoạt.\n\nBảo hiểm sức khỏe toàn diện cho nhân viên và người thân.\n\nMôi trường làm việc quốc tế, đa văn hóa.\n\nCơ hội học tập và phát triển kỹ năng liên tục.\n\nTrang bị công nghệ hiện đại, hỗ trợ chi phí học tập và nghiên cứu.",
    work_location: "Cầu Giấy, Hà Nội"
  },
  {
    id: "8f4b3a2c-1d7e-4f5a-9c6b-0d1e2f3a4b5c",
    job_title: "Nhà Khoa Học Dữ Liệu",
    job_link: "https://example.com/jobs/data-scientist",
    salary: "95.000.000 - 140.000.000 VNĐ",
    region: "Đà Nẵng",
    job_company: "Công ty Phân Tích Insight",
    experience: "2-6 năm",
    job_level: "Chuyên viên đến Chuyên viên cao cấp",
    education_level: "Thạc sĩ hoặc Tiến sĩ trong lĩnh vực liên quan",
    related_job: "Kỹ sư Học máy, Chuyên viên Phân tích dữ liệu",
    required_skills: "Python, R, SQL, Machine Learning, Thống kê, Trực quan hóa dữ liệu",
    job_description: "Tham gia vào đội ngũ khoa học dữ liệu để phát triển các giải pháp sáng tạo sử dụng phân tích nâng cao, học máy và kỹ thuật AI để giải quyết các vấn đề kinh doanh phức tạp.\n\nXây dựng và triển khai các mô hình dự đoán, phân loại và phân tích xu hướng từ dữ liệu lớn.\n\nPhối hợp với các bộ phận kinh doanh để xác định cơ hội và thách thức có thể giải quyết bằng phân tích dữ liệu.\n\nPhát triển các thuật toán tự động hóa và tối ưu hóa quy trình kinh doanh.\n\nThiết lập hệ thống theo dõi hiệu suất và đánh giá mô hình.",
    job_requirement: "Nền tảng toán học vững chắc, kinh nghiệm với các framework học máy.\n\nKhả năng chuyển đổi câu hỏi kinh doanh thành truy vấn dữ liệu và mô hình phân tích.\n\nThành thạo Python, R và các thư viện phân tích dữ liệu như Pandas, NumPy, Scikit-learn.\n\nKinh nghiệm làm việc với các công cụ trực quan hóa dữ liệu như Tableau, PowerBI.\n\nHiểu biết về quy trình phát triển phần mềm và quản lý vòng đời dự án phân tích.\n\nKỹ năng giao tiếp tốt, có khả năng giải thích các khái niệm kỹ thuật phức tạp cho đối tượng không chuyên.",
    job_benefit: "Tùy chọn làm việc tại nhà linh hoạt.\n\nTrợ cấp đào tạo liên tục, cơ hội tham dự hội nghị quốc tế.\n\nMôi trường nghiên cứu đổi mới, khuyến khích sáng tạo và thử nghiệm.\n\nCơ hội làm việc với dữ liệu đa dạng từ nhiều ngành công nghiệp.\n\nTham gia các dự án có tác động xã hội cao.\n\nPhụ cấp công nghệ, sách và các nguồn tài nguyên học tập chuyên ngành.",
    work_location: "Trung tâm Thành phố Đà Nẵng"
  },
  {
    id: "2a1b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d",
    job_title: "Kỹ Sư DevOps",
    job_link: "https://example.com/jobs/devops",
    salary: "85.000.000 - 120.000.000 VNĐ",
    region: "Thành phố Hồ Chí Minh",
    job_company: "Công ty Giải Pháp CloudNative",
    experience: "3+ năm",
    job_level: "Chuyên viên cao cấp",
    education_level: "Cử nhân CNTT hoặc tương đương",
    related_job: "SRE, Quản trị hệ thống, Kỹ sư Điện toán đám mây",
    required_skills: "AWS, Kubernetes, Docker, Terraform, CI/CD, Linux",
    job_description: "Chúng tôi đang tìm kiếm Kỹ sư DevOps để giúp xây dựng và duy trì cơ sở hạ tầng điện toán đám mây cùng quy trình triển khai liên tục.\n\nThiết kế, triển khai và quản lý hệ thống hạ tầng trên nền tảng cloud AWS.\n\nXây dựng và duy trì quy trình CI/CD, tự động hóa việc triển khai ứng dụng.\n\nQuản lý container hóa với Docker và Kubernetes, đảm bảo tính sẵn sàng cao của hệ thống.\n\nTriển khai các giải pháp Infrastructure as Code sử dụng Terraform.\n\nXây dựng hệ thống giám sát, cảnh báo và phân tích logs toàn hệ thống.",
    job_requirement: "Kinh nghiệm với container hóa, Infrastructure as Code và dịch vụ điện toán đám mây.\n\nKiến thức về công cụ giám sát và thực hành bảo mật tốt nhất.\n\nThành thạo Linux và kỹ năng scripting (Bash, Python).\n\nKinh nghiệm với Kubernetes và quản lý cluster ở quy mô lớn.\n\nHiểu biết về các khái niệm bảo mật, mạng và cân bằng tải.\n\nKỹ năng xử lý sự cố hệ thống và khả năng làm việc trong môi trường áp lực cao.",
    job_benefit: "Thời gian làm việc linh hoạt, ngân sách đào tạo hấp dẫn.\n\nTrang bị thiết bị hiện đại, chế độ làm việc từ xa kết hợp.\n\nHoạt động team building thường xuyên, môi trường làm việc quốc tế.\n\nCơ hội tham gia các dự án sáng tạo và áp dụng công nghệ mới nhất.\n\nBảo hiểm sức khỏe cao cấp và các phúc lợi gia đình.\n\nCơ hội thăng tiến nhanh, đánh giá năng lực định kỳ với mức thưởng hấp dẫn.",
    work_location: "Thủ Đức, Thành phố Hồ Chí Minh"
  }
];